# Matrix operations for matrices, for which each entry is a function $f_{i,j} : \mathbb{R} \to \mathbb{R}$
## Implementation of an (point-wise) addition and multiplication of such matrices 


#### Some imports

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.image as mpimg


The Code part:

In [2]:
def add_functions(f, g):
    return lambda x: f(x) + g(x)
def multiply_functions(f, g):
    return lambda x: f(x) * g(x)

def validate_function(in_1: np.ndarray,in_2:np.ndarray, op) -> np.ndarray or None:
    try:
        assert in_1.shape == in_2.shape
        return in_1, in_2
    except AssertionError:
        print(f'The shapes of the two matrices you want to operate on, must be equivalent,',
        'which they are not.')
        ans = input('Would you like to use padding to solve this problem? Then please answer with <Yes>: ')
        if ans == 'Yes' or ans == '<Yes>':
            if op == add_functions:
                fill_func = np.array([lambda x: x*0])
            elif op == multiply_functions:
                fill_func = np.array([lambda x: x**0])
            if in_1.shape[0] <= in_2.shape[0] and in_1.shape[1] <= in_2.shape[1]:
                matrix = fill_func.repeat(in_2.size).reshape(in_2.shape)
                matrix[0:len(in_1), 0:len(in_1[0])] = in_1
                in_1 = matrix
            elif in_1.shape[0] >= in_2.shape[0] and in_1.shape[1] <= in_2.shape[1]:
                matrix = fill_func.repeat(in_1.shape[0]*in_2.shape[1]).reshape((in_1.shape[0], in_2.shape[1]))
                matrix[0:len(in_1), 0:len(in_1[0])] = in_1
                in_1 = matrix
                matrix = fill_func.repeat(in_1.shape[0]*in_2.shape[1]).reshape((in_1.shape[0], in_2.shape[1]))
                matrix[0:len(in_2), 0:len(in_2[0])] = in_2
                in_2 = matrix
            elif in_1.shape[0] >= in_2.shape[0] and in_1.shape[1] >= in_2.shape[1]:
                matrix = fill_func.repeat(in_1.size).reshape(in_1.shape)
                matrix[0:len(in_2), 0:len(in_2[0])] = in_2
                in_2 = matrix
            elif in_1.shape[0] <= in_2.shape[0] and in_1.shape[1] >= in_2.shape[1]:
                matrix = fill_func.repeat(in_2.shape[0]*in_1.shape[1]).reshape((in_2.shape[0], in_1.shape[1]))
                matrix[0:len(in_1), 0:len(in_1[0])] = in_1
                in_1 = matrix
                matrix = fill_func.repeat(in_2.shape[0]*in_1.shape[1]).reshape((in_2.shape[0], in_1.shape[1]))
                matrix[0:len(in_2), 0:len(in_2[0])] = in_2
                in_2 = matrix
            return in_1, in_2
        else:
            raise ValueError('Due to incompatibility problems the operation of these two matrices',
                    'is not defined and will therefore be stopped.')

def point_wise_operation(in_1: np.ndarray,in_2:np.ndarray, op) -> np.ndarray:
    
    """This function takes 3 input arguments: two matrices which have entries that are functions and one operator.
        It returns a matrix of the point wise implementation of the operator on the 2 matrices that were given as the input arguments."""

    dimension_check = validate_function(in_1, in_2, op)
    in_1, in_2 = dimension_check
    output = np.ndarray(shape=(len(in_1), len(in_2[0])), dtype=object)
    for i in range(len(in_1)):
        for j in range(len(in_2[0])):
            output[i][j] = op(in_1[i][j], in_2[i][j])
    return output
    

Test Part for matrices with the same dimensions:

In [3]:
m1 = np.array([[lambda x: x, lambda x: x**2 +5 ], [lambda x: x**3, lambda x: x**4]])
m2 = np.array([[lambda x: x**5 + 4, lambda x: x**6], [lambda x: x**7 -7, lambda x: x**8]])

m3 = point_wise_operation(m1, m2, add_functions)
print(m3)

[[<function add_functions.<locals>.<lambda> at 0x0000025EE5D260E0>
  <function add_functions.<locals>.<lambda> at 0x0000025EE5D26170>]
 [<function add_functions.<locals>.<lambda> at 0x0000025EE5D26200>
  <function add_functions.<locals>.<lambda> at 0x0000025EE5D26290>]]


In [4]:
m1 = np.array([[lambda x: x, lambda x: x**2 +5 ], [lambda x: x**3, lambda x: x**4]])
m2 = np.array([[lambda x: x**5 + 4, lambda x: x**6], [lambda x: x**7 -7, lambda x: x**8]])

m5 = point_wise_operation(m1, m2, multiply_functions)
print(m5)

[[<function multiply_functions.<locals>.<lambda> at 0x0000025EE5D26B00>
  <function multiply_functions.<locals>.<lambda> at 0x0000025EE5D26B90>]
 [<function multiply_functions.<locals>.<lambda> at 0x0000025EE5D26C20>
  <function multiply_functions.<locals>.<lambda> at 0x0000025EE5D26CB0>]]


Test part for matrices with differing dimensions:

In [5]:
m4 = np.array([[lambda x: x, lambda x: x**2 +5 ]])
m2 = np.array([[lambda x: x**5 + 4, lambda x: x**6], [lambda x: x**7 -7, lambda x: x**8]])

m6 = point_wise_operation(m4, m2, add_functions)
print(m6)

The shapes of the two matrices you want to operate on, must be equivalent, which they are not.
[[<function add_functions.<locals>.<lambda> at 0x0000025EE5D26D40>
  <function add_functions.<locals>.<lambda> at 0x0000025EE5D27370>]
 [<function add_functions.<locals>.<lambda> at 0x0000025EE5D27400>
  <function add_functions.<locals>.<lambda> at 0x0000025EE5D27490>]]


In [6]:
m4 = np.array([[lambda x: x, lambda x: x**2 +5 ]])
m2 = np.array([[lambda x: x**5 + 4, lambda x: x**6], [lambda x: x**7 -7, lambda x: x**8]])

m7 = point_wise_operation(m4, m2, multiply_functions)
print(m7)

The shapes of the two matrices you want to operate on, must be equivalent, which they are not.


ValueError: ('Due to incompatibility problems the operation of these two matrices', 'is not defined and will therefore be stopped.')

In [13]:
m4 = np.array([[lambda x: x, lambda x: x**2 +5, lambda x: x*3 + 5**x ]])
m2 = np.array([[lambda x: x**5 + 4, lambda x: x**6], [lambda x: x**7 -7, lambda x: x**8]])

m7 = point_wise_operation(m2, m4, multiply_functions)
print(m7)

The shapes of the two matrices you want to operate on, must be equivalent, which they are not.
[[<function multiply_functions.<locals>.<lambda> at 0x0000025EE6998160>
  <function multiply_functions.<locals>.<lambda> at 0x0000025EE69981F0>
  <function multiply_functions.<locals>.<lambda> at 0x0000025EE6998280>]
 [<function multiply_functions.<locals>.<lambda> at 0x0000025EE6998310>
  <function multiply_functions.<locals>.<lambda> at 0x0000025EE69983A0>
  <function multiply_functions.<locals>.<lambda> at 0x0000025EE6998430>]]


#### Implementation of function evaluation for such matrices

In [7]:
def evaluate_matrix(in_matrix: np.ndarray, x: float) -> np.ndarray or None:
    
    """This function takes a matrix of functions and a number x and returns a matrix 
        of the evaluation of the functions in the input matrix at x. In case the point_wise_operation
        did not return a matrix due to dimensions that don't match, evaluation won't be possible"""

    output = np.ndarray(shape=(len(in_matrix), len(in_matrix[0])), dtype=object)
    for i in range(len(in_matrix)):
        for j in range(len(in_matrix[0])):
            output[i][j] = in_matrix[i][j](x)
    return output

Test part:

In [9]:
x = 2
print(evaluate_matrix(m3, x))

[[38 73]
 [129 272]]


In [10]:
x = 5
print(evaluate_matrix(m5, x))

[[15645 468750]
 [9764750 244140625]]


In [11]:
x = 3
print(evaluate_matrix(m6, x))

[[250 743]
 [2180 6561]]


In [14]:
x = 2
print(evaluate_matrix(m7, x))

[[72 576 31]
 [121 256 1]]
